llm:
  filter_model:
    name: "gpt-4-1106-preview"
    query_cost_limit_usd: 0.1
    context_size_limit:
      4096 # Mandatory in some cases as langchain doesn't
      # provide this info for all models
    prompt_to_completion_len_ratio: 0.4 # A guesstimate
  summary_model:
    name: "gemini-1.0-pro"
    query_cost_limit_usd: 0.1
    cost_per_1k_characters_usd: 0.000125
    prompt_to_completion_len_ratio: 3.0 # A guesstimate
web:
  user_agent: >
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 
    (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
sources:
  with_summary:
    - name: "researchhub"
      subspaces: [] # all
  without_summary:
    - name: "reddit"
      subspaces: ["machinelearning"] # subreddit names
    - name: "hackernews"
      subspaces: [] # all
    - name: "futuretools"
      subspaces: [] # all
  articles_per_source_limit: 20
